
[websocket]
url = "ws://10.243.197.206:8080"
frame_size = 960

[opus]
sample_rate = 16000
channels = 1

[logger]
level = "debug"
file_path = "../.log"
# mode = "append" or "overwrite"
# 默认值为 "append"
mode = "overwrite"
